path: /case-studies
hero:
  subtitle: Discover & Educate
  title: Case Studies
actionBar:
  enabled: true
meta:
  favicon: /images/mark_light_bg.png
  title: Read Our Case Studies | Stoplight
  twitter:
    title: Read Our Case Studies | Stoplight
    username: '@stoplightio'
