path: '/demo'
hero:
  bgColor: black
  subtitle: >-
    Stoplight on average shows a 36% gain in engineering time and increases quality 30%.
  title: 'Request a demo'
hubspot:
  formId: "7ae2bb42-67a6-4ee3-9ac5-ff21d87812ea"
  portalId: '4892910'
customers:
  - /images/ea.png
  - /images/logo_arkea_transparent.png
  - /images/chargify-new-logo.png
  - /images/deutsche_bank.png
  - /images/customers/quicken.png
  - /images/logo-sendgrid.png
  - /images/shopgate.png
  - /images/spotify.png
  - /images/tivo.png
  - /images/logo_zendesk.png
testimonials:
  - author: Kin Lane
    image: /images/testimonials/kin_lane.jpeg
    quote: >-
      I feel like Stoplight has the potential to shift the landscape pretty
      significantly, something I haven't seen any API service provider do in a
      while.
    role: API Evangelist
  - author: 'Carlos Lozano '
    image: /images/carlos_testimonial.jpeg
    quote: >-
      When it comes to specification markup and documentation, the order of
      magnitude has gone from days to hours.
    role: 'Senior Enterprise Architect, GFT Group'
  - author: John Vajda
    image: /images/testimonials/john_vajda.jpeg
    quote: >-
      Stoplight has been a serious game changer for JumpCloud’s API development!
      We love all the rich design, documentation and testing features, which has
      enabled us to design awesome APIs for our customers.
    role: 'Product Manager, JumpCloud'
  - author: Gil Barbara
    image: /images/testimonials/gil.jpeg
    quote: >-
      Stoplight provides a centralized, testable and reliable source for our
      APIs.
    role: 'Frontend Engineer, AMARO'
