header:
  items:
    - links:
        - href: /design
          icon:
            - fas
            - paint-brush
          subtitle: Use our visual designer to manage OpenAPI (Swagger) 10x faster.
          title: Design
          titleColor: blue
        - href: /documentation
          icon:
            - fas
            - book
          subtitle: 'Increase customer adoption with beautiful, functional documentation.'
          title: Documentation
          titleColor: green
        - href: /testing
          icon:
            - fas
            - flask
          subtitle: 'Leverage OpenAPI to test, automate, and debug web APIs.'
          title: Testing
          titleColor: orange
        - href: /mocking
          icon:
            - fas
            - server
          subtitle: >-
            Parallelize development with one click mock servers, powered by
            OpenAPI.
          title: Mocking
          titleColor: grey-darkest
      title: Products
      width: 400
    - links:
        - href: 'http://docs.stoplight.io/'
          icon:
            - fas
            - book
          subtitle: Learn how to use Stoplight
          title: Help Center
          titleColor: blue
        - href: 'https://community.stoplight.io/'
          icon:
            - fas
            - users
          subtitle: Join the Stoplight community
          title: Community
          titleColor: green
        - href: 'http://blog.stoplight.io/'
          icon:
            - fas
            - rss
          subtitle: Stay up to date on Stoplight
          title: Blog
          titleColor: orange
        - icon:
            - fas
            - comments
          onClick: intercom
          subtitle: Ask us anything
          title: Chat
          titleColor: grey-darkest
      title: Resources
      width: 350
    - links:
        - href: /about
          icon:
            - fas
            - users
          title: About Us
        - href: /case-studies
          icon:
            - fas
            - graduation-cap
          title: Case Studies
      title: Company
      width: 250
    - href: /pricing
      title: Pricing
actionBar:
  buttons:
    - color: purple
      href: mailto://support@stoplight.io
      outlined: true
      title: Request a Demo
    - color: purple
      href: 'https://next.stoplight.io'
      title: Create a Free Account
  enabled: false
  text: Getting started is easy. Be up and running in minutes.
footer:
  columns:
    - links:
        - href: /design
          title: Design
        - href: /documentation
          title: Documentation
        - href: /testing
          title: Testing
        - href: /mocking
          title: Mocking
      title: Products
    - links:
        - href: 'https://docs.stoplight.io'
          title: Help Center
        - href: 'https://community.stoplight.io'
          title: 'Community '
        - href: 'https://blog.stoplight.io'
          title: Blog
        - href: https://press.stoplight.io
          title: Press
      title: Resources
    - links:
        - href: /about
          title: About Us
        - href: /case-studies
          title: Case Studies
        - href: mailto://support@stoplight.io
          title: Contact Us
      title: Company
  social:
    - href: 'https://twitter.com/stoplightio'
      icon:
        - fab
        - twitter
    - href: 'https://www.linkedin.com/company/stoplight'
      icon:
        - fab
        - linkedin
    - href: 'https://www.github.com/stoplightio'
      icon:
        - fab
        - github
meta:
  description: >-
    Stoplight, providing engineering teams with the best way to document, test,
    and build web APIs.
  favicon: /favicons/favicon.ico
  image: /images/home-hero.png
  title: Stoplight
  twitter:
    description: >-
      Stoplight, providing engineering teams with the best way to document,
      test, and build web APIs.
    image: /images/home-hero.png
    title: Stoplight
    username: '@stoplightio'
  url: 'https://stoplight.io'
googleTagManager: GTM-58LWL5P
